FROM php:7.3.12-fpm

LABEL maintainer="Sharapov A. <alexander@sharapov.biz>"

RUN addgroup --gid 1000 bexpr
RUN adduser --uid 1000 --gid 1000 bexpr

COPY php-pool.conf /usr/local/etc/php-fpm.d/www.conf
COPY php.ini /usr/local/etc/php/conf.d/php.ini

USER bexpr

CMD ["php-fpm"]

WORKDIR /var/www

# check if response header returns 204 code OR die
HEALTHCHECK --interval=5s --timeout=5s --retries=5 CMD [ "204" = "$(curl -s -o /dev/null -w "%{http_code}" http://localhost/api/ping)" ] || exit 1
