FROM nginx:alpine

LABEL maintainer="Sharapov A. <alexander@sharapov.biz>"

RUN addgroup -g 1000 -S bexpr && adduser -H -D -u 1000 -h /var/cache/nginx -G bexpr bexpr

COPY default.conf /etc/nginx/nginx.conf

RUN touch /var/run/nginx.pid \
 && chown -Rf bexpr:bexpr \
    /var/run/nginx.pid \
    /var/cache/nginx \
    /var/log/nginx

RUN apk add --no-cache curl

USER bexpr

EXPOSE 8000

HEALTHCHECK --interval=5s --timeout=5s --retries=5 CMD [ "200" = "$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:3423/api/ping)" ] || exit 1
