services:
  - docker

before_install:
  - docker image build -t bixpressive_test_phpfpm:latest -f docker/test/Dockerfile.phpfpm docker/test

install:
  - docker run -it -v=$(pwd):/var/www bixpressive_test_phpfpm:latest composer install

script:
  - phpunit
